// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy2EvAlYBvzd9_O9qj0VQURH-xUvbqzSM',
    appId: '1:423691984647:web:4d3ecc09997cbd032bafa2',
    messagingSenderId: '423691984647',
    projectId: 'harnkeng',
    authDomain: 'harnkeng.firebaseapp.com',
    storageBucket: 'harnkeng.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLp7iqHKOy93LqyaR0Uimlrl2dm4rQvOI',
    appId: '1:423691984647:android:7715f2a06c83b1192bafa2',
    messagingSenderId: '423691984647',
    projectId: 'harnkeng',
    storageBucket: 'harnkeng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBduUFS86xYp9BWGXtliELionFmKhVZxWE',
    appId: '1:423691984647:ios:ca48b666d4c293392bafa2',
    messagingSenderId: '423691984647',
    projectId: 'harnkeng',
    storageBucket: 'harnkeng.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBduUFS86xYp9BWGXtliELionFmKhVZxWE',
    appId: '1:423691984647:ios:ca48b666d4c293392bafa2',
    messagingSenderId: '423691984647',
    projectId: 'harnkeng',
    storageBucket: 'harnkeng.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy2EvAlYBvzd9_O9qj0VQURH-xUvbqzSM',
    appId: '1:423691984647:web:45bd7e90dd4756b52bafa2',
    messagingSenderId: '423691984647',
    projectId: 'harnkeng',
    authDomain: 'harnkeng.firebaseapp.com',
    storageBucket: 'harnkeng.firebasestorage.app',
  );

}